### ISSUE TITLE
Almanca kelime tanımları için 'Deutsch' butonuna basmak gerekiyor

### ISSUE THREAD

**Issue by akyurekyunus** [mtunad/multisozlukextension#15]
Merhaba, 

Çok basit ve pratik bir program yazmışsınız. Öncelikle bunun için teşekkür ediyorum. Bağış yapabileceğimiz bir yerler varsa lütfen bildirin. 

Şimdi belki küçük bir nokta ama size bildirmek istedim. Bildiğiniz gibi uygulamana standart olarak baktığı yabancı dil ingilizce. Fakat ben Almanca ve İngilizceyi günlük olarak kullanmak durumunda olan biriyim. Durum böyle olunca, Almanca kelimeler aradığımda kelimenin anlamı direkt olarak bulunamıyor. Bunun için 'Deutsch' butonuna basmam gerekiyor. 

Bunun çözmek için iki adımlı bir önerim var: 

1) Bir kelime aradığımızda program tüm sözlüklere bakıyor ve anlamları buluyor. 
2) Eğer bir kelimenin karşılığı sadece bir sözlükte varsa, kelimenin anlamını o sözlükten gösteriyor. 

Örnek: zunehmen --> (İngilizce karşılığı: **null**, TDK karşılığı: **null**, eksi: **null**, Deutsch karşılığı: **increase**...) --> Deutsch tabı açılır ve kelime anlamı gösterilir.

Tabii şimdi bazı kelimerin İngilizce VE Almanca karşılığı olabilir, örnek team. Ama bu sözcükler zaten büyük ihtimalle çoğunluğun bildiği sözcükler olduğu için sorun olacağını zannetmiyorum.

**Comment by mtunad** [comment]
Mantıklı aslında. Tek tek her şeye sorgu göndermek yerine ayarlara "Önce Almanca karşılığına bak" seçeneği koyabilirim. Bu sayede eğer kelimenin Almanca-İngilizce karşılığı varsa onu gösterir, yoksa İngilizce getirmeye çalışır. Baştan toparlamam ufak tefek çok fazla kullanıcı deneyimi olayı var. Ama bu görece kolay implemente edilebilir gibi. Bu hafta işlerim var ama önümüzdeki haftaya halletmeye çalışacağım.

**Comment by akyurekyunus** [comment]
Değişiklikleri yapabilirsen çok güzel olur. Kolay gelsin (Y)

**Comment by mtunad** [comment]
Ekledim yakında yayınlayacağım. 9fc1923f367c1bcf49c2bfa24c2e27be157a2469

Mantıksal olarak toparlamam gereken çok şeyi var eklentinin. Şimdilik ayarlara en sona "önce almanca arama yap" seçeneği ekledim. Aktifleştirince önce Almanca-İngilizce sözlükte arıyor, bulamazsa tureng'e geçiyor. Ama tabi bidirectional arama olunca çoğunlukla tureng aramasına düşmüyor. Neyse, belki bir gün toparlarken bu kullanım deneyimini de düşünerek ele alacağım
