### ISSUE TITLE
Chrome v 90.0.4430.93 yüklenememe sorunu

### ISSUE THREAD

**Issue by omerakgoz34** [mtunad/multisozlukextension#16]
Chrome v90.0.4430.93 sürümüne 1.0.13 sürümü yüklenmiyor
![Screenshot_13](https://user-images.githubusercontent.com/49201485/116297164-aaae7580-a7a3-11eb-8430-b51f45219e4f.png)  
![Screenshot_14](https://user-images.githubusercontent.com/49201485/116297176-ad10cf80-a7a3-11eb-91dd-1f9a60a01634.png)  
Daha yeni format attım PC'ye ve yüklenmeyen/çalışmayan tek eklenti multi sözlük oldu :(
Nedenini de anlamadım, yıllardır ilk defa böyle bir şey oluyor.

**Comment by mtunad** [comment]
Bildirim için teşekkürler. Evet bir sorun var. Düzeltince not düşeceğim buraya

**Comment by mtunad** [comment]
yaygın bir chrome web store hatasıymış. şimdi düzelmiş olmalı

**Comment by omerakgoz34** [comment]
Evet, yeni güncelleme çıkmış ve sihirli bir şekilde kendiliğinden düzelmiş :P
